### Variables
@baseUrl=https://ai-dev-search-free.search.windows.net
@apiKey=A4iH0OQ7x0ZxC9jAVdibRG6Uftt92KT5zOVBgDJhn2AzSeBLbcrx
@apiVersion = 2020-06-30

### Update the skillset
PUT {{baseUrl}}/skillsets/margies-skillset?api-version={{apiVersion}}
Content-Type: application/json
api-key: {{apiKey}}

< ./skillset.json

### Update the index
PUT {{baseUrl}}/indexes/margies-index?api-version={{apiVersion}}
Content-Type: application/json
api-key: {{apiKey}}

< ./index.json

### Update the indexer
PUT {{baseUrl}}/indexers/margies-indexer?api-version={{apiVersion}}
Content-Type: application/json
api-key: {{apiKey}}

< ./indexer.json

### Reset the indexer
POST {{baseUrl}}/indexers/margies-indexer/reset?api-version={{apiVersion}}
Content-Type: application/json
Content-Length: 0
api-key: {{apiKey}}

### Run the indexer
POST {{baseUrl}}/indexers/margies-indexer/run?api-version={{apiVersion}}
Content-Type: application/json
Content-Length: 0
api-key: {{apiKey}}