[project]
name = "evaluations-py"
version = "0.1.0"
description = "Azure AI Foundry Evaluations Demo"
readme = "readme.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "azure-identity==1.19.0",
    "openai==1.109.1",
    "python-dotenv==1.0.1",
    "azure-ai-evaluation==1.13.7",
    "azure-ai-projects==1.0.0",
]