[project]
name = "rag-azure"
version = "0.1.0"
description = "Azure AI Foundry RAG Demo"
readme = "readme.md"
requires-python = ">=3.9"
dependencies = [
    "azure-ai-projects==1.0.0b12",
    "azure-ai-inference==1.0.0b9",
    "azure-ai-evaluation==1.9.0",
    "azure-identity==1.23.1",
    "azure-search-documents==11.5.3",
    "python-dotenv==1.1.1",
    "azure-storage-blob==12.25.1",
    "uvicorn[standard]==0.35.0",
    "tqdm==4.67.1",
]